### ISSUE TITLE
x.COB file not COBOL? 

### ISSUE THREAD

**Issue by markons** [cschneid-the-elder/mapa#104]
I get following message at parsing a small (SQL) COBOL program at running the CobolTree under OMVS:

"[Tue Mar 29 08:48:42 GMT+01:00 2022] INFO: getprml0.cob not COBOL?"

I can run the same parsing under Windows for the program without any error.

Another question for the same running environment: how can I define the -file parameter for an OMVS file?
My guess was something like -file "//'my-mvs-file'"
...but the file name was not recognized by the app.

**Comment by markons** [comment]
As for the first issue: sorry, I must correct myself. My sample does not run on Windows as well. It seems like the parser checks some criterias to recognize if the source a valid Cobol program is, but I do not know this criterias. 
As for the second issue: the program works with standard i/o, no JZOS, insofar has no access to MVS files, isn't it?

**Comment by cschneid-the-elder** [comment]
There's a check for an Identification Division, if it's missing then the code presumes it's not dealing with a COBOL program.  As for running the code on OMVS, I have no access to a z/OS machine and cannot test there.  You are correct, the program uses standard Java I/O, no access to MVS files.

**Comment by markons** [comment]
Thanks first. regarding JZOS, I can write an interface to copy the MVS files into OMVS, no problem.
Regarding "...not COBOL": the program is definitiv valid COBOL code.

 lpar       /u/xxxxxx/hello.cob                       
 Command ===>                                          
 ****** ***************************** Top of Data *****
 000001        IDENTIFICATION DIVISION.                
 000002        PROGRAM-ID. HELLO                       
 000003       *                                        
 000004        ENVIRONMENT DIVISION.                   
 000005                                                
 000006       *                                        
 000007        DATA DIVISION.                          
 000008        WORKING-STORAGE SECTION.                
 000009        77 VALTOZO PIC X(30).                   
 000010       *                                        
 000011        PROCEDURE DIVISION.                     
 000012            DISPLAY "HELLO WORLD!".             
 000013            MOVE 'GABOR' TO VALTOZO.            
 000014            DISPLAY VALTOZO. 

lpar </u/xxxxxx>java -jar CallTree.jar -copy /u/ -file hello.cob -out parsed.txt                                                                               

[Mon Apr 04 07:36:48 GMT+01:00 2022] INFO: Logger Name: TestIntegration         
[Mon Apr 04 07:36:48 GMT+01:00 2022] INFO: Processing hello.cob                 
**[Mon Apr 04 07:36:49 GMT+01:00 2022] INFO: hello.cob not COBOL?**                 
[Mon Apr 04 07:36:49 GMT+01:00 2022] INFO: writing to parsed.txt                
[Mon Apr 04 07:36:49 GMT+01:00 2022] INFO: Processing complete

**Comment by markons** [comment]
Sorry, one can see the spaces in my COBOL screenshot not, but valid in reality.

**Comment by cschneid-the-elder** [comment]
I pasted your code into a file locally and it was recognized as COBOL and processed successfully.  I can force the error you see by putting IDENTIFICATION DIVISION in column 1.

So something is different between your file and my copy of your file, or your environment and mine.

There appear to be many caveats on the z/OS `cp` command.  You might want to re-verify the spacing is correct (IDENTIFICATION DIVISION begins in column 8 and the comment indicators are in column 7 and so forth) with the `cat` command at a Unix prompt.  On rare occasions obrowse, oedit, and oview try to be helpful and only succeed in hiding necessary information.  You could also use oview and use the COLS command to verify statements are where they need to be.

The only other thing that comes to mind is code page issues.  You might have to set the code page of your input file on the command line something like...

`java -Dfile.encoding=your-file-code-page -jar CallTree.jar -copy /u/ -file hello.cob -out parsed.txt`

...but that's just a guess.  I think it's more likely that the COBOL statements have been moved to the wrong columns by something subtle in the `cp` process.  But that's really just a guess too.

**Comment by markons** [comment]
I've written some minimal code to check the behavior:

public static void main(String[] args) throws IOException {
        String fileName = args[0];
       
        readUsingBufferedReader(fileName);
        if (isCobol) {
            System.out.println("***YESS it is a COBOL file!***");
        }
        else {
           System.out.println("***NO it is NOT a COBOL file!***"); 
        }
}
private static void readUsingBufferedReader(String fileName) throws IOException {
        File file = new File(fileName);
        FileReader fr = new FileReader(file);
        BufferedReader br = new BufferedReader(fr);
        String line;
        System.out.println("Read text file using BufferedReader");
        while ((line = br.readLine()) != null) {
            //process the line
            if (line.length() > 22) {                
                if (line.substring(7, 22).equals("IDENTIFICATION ")) {
                    isCobol = true;
                }
            }
            System.out.println(line);
        }
        //close resources
        br.close();
        fr.close();
    }

I've uploaded this fat jar onto our mainframe LPAR (just like the mapa jar) per WinScp, run it against the hello.cob, here the result:

LPAR0 </u/xx8yy22>java -jar JavaReadFile.jar hello.cob  
Read text file using BufferedReader                    
       **IDENTIFICATION DIVISION.                        
       ...
       END PROGRAM HELLO.      
***YESS it is a COBOL file!***** 
LPAR0 </u/xx8yy22>        

Insofar, the problem is:
1/ no format issue
2/ no coding issue(?)

**Comment by cschneid-the-elder** [comment]
I believe you have proven it's not a format issue.

I think there may be an issue with code page, and here's why I think that: I looked at the code generated by ANTLR and it's full of Unicode constants.

I used `iconv` to convert my copy of your code to code page 37 (what we used to call EBCDIC)...

`iconv -t IBM037 <hello.cob >hello1.cob`

...and ran the CallTree.jar code against that.  I got the "not COBOL" error.

I used iconv to convert hello1.cob to UTF-8...

`iconv -f IBM037 -t UTF-8 <hello1.cob >hello2.cob`

 ...and ran the CallTree.jar again, and hello2.cob was processed successfully.

So, you might want to try using `iconv` to make certain that hello.cob is the code page expected by the generated code, which appears to be UTF-8.  If your system's default code page is 037 then that would look like...

`iconv -f IBM037 -t UTF-8 <hello.cob >hello2.cob`

...but you might be using code page 1140 or 500 or one of the others commonly in use on z/OS.  It's possible this doesn't matter for plain text, and hello.cob is certainly just plain text, but I'm really not sure.  You could just try one as a test and see if it fixes the problem.

z/OS `iconv` documentation: https://www.ibm.com/docs/en/zos/2.5.0?topic=scd-iconv-convert-characters-from-one-code-set-another

z/OS `cp` documentation on automatic code page conversions: https://www.ibm.com/docs/en/zos/2.5.0?topic=descriptions-cp-copy-file#cp__cpfiletag

**Comment by markons** [comment]
Thanks first for the hints. Unfortunately, no success:

LPAR0 </u/xx8yy22>ls -lT hello1.cob                                              
**t UTF-8**       T=on  -rwxrwxrwx   1 XX8YY22  UC$DFLT      362 Apr  8 15:23 hello1
.cob                                                                            
LPAR0 </u/xx8yy22>java -jar CallTree.jar -copy /u/ -file hello1.cob -out parsed.t
xt                                                                              
[Sun Apr 10 14:07:04 GMT+01:00 2022] INFO: Logger Name: TestIntegration         
[Sun Apr 10 14:07:05 GMT+01:00 2022] INFO: Processing hello1.cob                
**[Sun Apr 10 14:07:06 GMT+01:00 2022] INFO: hello1.cob not COBOL?**                
[Sun Apr 10 14:07:06 GMT+01:00 2022] INFO: writing to parsed.txt                
[Sun Apr 10 14:07:06 GMT+01:00 2022] INFO: Processing complete

**Comment by markons** [comment]
Can one debug the related class to show what Java see as "IDENTIFICATION DIVISION", or any line of the COBOL source?

**Comment by markons** [comment]
/hello1.cob         
d ===>                             
 ***************************** Top 
 ----+----1----+----2----+----3----
               IDENTIFICATION DIVISION.   
 2222222444454444454442445454442222
 0000000945E49693149FE0496939FEE000

...as USS/OEDIT sees it.

**Comment by cschneid-the-elder** [comment]
If you generate and compile the code for the preprocessor grammars (the CobolPreprocessorLexer.g4 and CobolPreprocessorParser.g4 files) then you can use ANTLR's test rig to see what the Lexer sees.

The Makefile may not work on z/OS USS, it presumes GNU Make, so the commands to generate the code for the grammars would be...

`java -jar antlr-4.9.2-complete.jar -listener src/CobolPreprocessorLexer.g4`
`java -jar antlr-4.9.2-complete.jar -listener src/CobolPreprocessorParser.g4`

...and then to compile...

'javac -d ./class -cp "./class:antlr-4.9.2-complete.jar" ./src/CobolPreprocessorLexer.java`
'javac -d ./class -cp "./class:antlr-4.9.2-complete.jar" ./src/CobolPreprocessorParser.java`
'javac -d ./class -cp "./class:antlr-4.9.2-complete.jar" ./src/CobolPreprocessorParserBaseListener.java`
'javac -d ./class -cp "./class:antlr-4.9.2-complete.jar" ./src/CobolPreprocessorParserListener.java`

...finally to see what the generated code sees when it parses hello1.cbl...

`java -cp ./class:.:./antlr-4.9.2-complete.jar org.antlr.v4.gui.TestRig CobolPreprocessor startRule -tokens < ./hello1.cbl`

...and the first few lines of that output should look like...

[@0,6:6=' ',<WS>,channel=1,1:6]
[@1,7:20='IDENTIFICATION',<IDENTIFICATION>,1:7]
[@2,21:21=' ',<WS>,channel=1,1:21]
[@3,22:29='DIVISION',<DIVISION>,1:22]
[@4,30:30='.',<'.'>,1:30]
[@5,31:31='\n',<NEWLINE>,1:31]
[@6,38:38=' ',<WS>,channel=1,2:6]
[@7,39:48='PROGRAM-ID',<IDENTIFIER>,2:7]
[@8,49:49='.',<'.'>,2:17]
[@9,50:50=' ',<WS>,channel=1,2:18]

**Comment by markons** [comment]
Thank you. Unfortunately, there are no listeners like CobolPreprocessorParserBaseListener.java / CobolPreprocessorParserListener.java in the ./src

**Comment by cschneid-the-elder** [comment]
You may not need the listeners, I'm not sure if the ANTLR TestRig requires them.  The listeners are generated by the second of these two commands...

`java -jar antlr-4.9.2-complete.jar -listener src/CobolPreprocessorLexer.g4`
`java -jar antlr-4.9.2-complete.jar -listener src/CobolPreprocessorParser.g4`

...but it's valid to leave off the `-listener` option, and then to compile...

`javac -d ./class -cp "./class:antlr-4.9.2-complete.jar" ./src/CobolPreprocessorLexer.java`
`javac -d ./class -cp "./class:antlr-4.9.2-complete.jar" ./src/CobolPreprocessorParser.java`

...followed by the...

`java -cp ./class:.:./antlr-4.9.2-complete.jar org.antlr.v4.gui.TestRig CobolPreprocessor startRule -tokens < ./hello1.cbl`

...command, which will let you see what the Lexer sees.

**Comment by cschneid-the-elder** [comment]
My apologies, but I am completely out of ideas.  I do not understand why things are behaving the way they are for you.  I really appreciate your patience with this process, but I'm just lost.  Again, my apologies.

**Comment by kaby76** [comment]
The undefined is caused because the Antlr Java tool was called with `-visitor` for CobolPreprocessorParser.g4. With the option, there's a reference to the Visitor class. So, after running the Antlr tool jar, check that it generated CobolPreprocessorParserVisitor.java among other files. If it did, it sounds like your classpath on the javac is not right.

```
java -jar  antlr-4.9.2-complete.jar -listener  *.g4
javac -cp antlr-4.9.2-complete.jar\;. *.java`
```

See if you need to substitue ':' or ';' as a path delimiter. I don't know how java works on that OS.

**Comment by cschneid-the-elder** [comment]
Unable to reproduce as it may have been z/OS specific.  Possible CCSID issue, but I just don't know and without access to a z/OS machine I cannot help.
