### ISSUE TITLE
alterIndexOptions should refer to clause usingBlock

### ISSUE THREAD

**Issue by mvhaasteren** [cschneid-the-elder/mapa#125]
https://github.com/cschneid-the-elder/mapa/blob/57b58b45a7352e50c333f7b876057bea8b558d78/db2z/src/DB2zSQLParser.g4#L2574

alterIndexOptions references 1 time the usingSpecification1.
This means a 1-time call being a "using stogroup" OR a secqty OR erase OR priqty. But it should be a loop ... hence it should reference the usingBlock clause.

**Comment by cschneid-the-elder** [comment]
The alterIndexOptions rule references the usingSpecification1 rule absent a subrule operator (?, +, *) but the
alterIndexOptions rule is itself referenced with the * subrule operator in the alterIndexStatement rule.  The last 10 test cases in sql_alterIndex have been added to test the use of more than one of the options in usingSpecification1.  The tests process successfully, I don't think a modification to the grammar is necessary - please let me know if I've misunderstood the issue.

**Comment by mvhaasteren** [comment]
Hmmm ... you are right. But I like to compare the ALTER INDEX with the ALTER TABLESPACE statements.. Same code (usingSpecification1), but differently referenced/encapsulated. And hence when writing rules (sonarqube) based on this syntax is then somewhat more difficult, as the search tree is slightly different.

I think that the alterTablespaceOptionsList, the alterPartionClause, the alterIndexOptions and the AlterIndexPartitionOptions should have the same flow. (And would make my life easier :-) ).

**Comment by cschneid-the-elder** [comment]
I think making peoples lives easier is what computers are _for_.   So let me see what I can do to help out.

**Comment by cschneid-the-elder** [comment]
Please look at DB2zSQLParser.g4 in branch db2z-issue-125a and let me know if that makes your life easier.

**Comment by mvhaasteren** [comment]
check ... yeah ... if you would merge branch db2z-issue-125a, my life in the realm of SonarQube rules IS easier :-).
Thanks Craig!

**Comment by cschneid-the-elder** [comment]
merge is done, glad I could help.
