### ISSUE TITLE
Simple fix for performance/overacceptance issue on if/then/else in CobolParser.g4

### ISSUE THREAD

**Issue by wfahle** [cschneid-the-elder/mapa#215]
Hi, we noticed a significant performance penalty that was getting all kinds of ambiguity in antlr when parsing a file with long chains of IF/THEN/ELSE/IF/... Running the ANTLR profiler pointed to ambiguities on the ifElse rule. My colleague noticed that ifThen and ifElse ought to be defined as follows (+ rather than *) because the whole point of NEXT SENTENCE is to fill in for when you don't have anything to say in the THEN or ELSE segment. You can't just have IF X EQUAL 3 END-IF; you need at least one statement there.

ifThen
   : THEN? (nextSentenceStatement | statement+)
   ;

ifElse
   : ELSE (nextSentenceStatement | statement+)
   ;

This removed the ambiguities and took parsing from 1.5 minutes down to 3 seconds for certain problematic files. This is because it was heading down the road of no statement there first, then backtracking massively to there being a statement there.

**Comment by cschneid-the-elder** [comment]
Thank you for pointing this out; it's been fixed, tested, and merged.
