### ISSUE TITLE
REVERSE_VIDEO = R E S E R V E etc.

### ISSUE THREAD

**Issue by wfahle** [cschneid-the-elder/mapa#219]
REVERSE != RESERVE in CobolLexer.g4

**Comment by cschneid-the-elder** [comment]
Fixed the typo in the lexer, also added missing Screen Section attributes to screenDescriptionEntry in the parser, also updated PIC_MODE in the lexer to popMode when it sees Screen Section attributes.  Tests pass, merged into master branch.

Thanks for letting me know about the typo.
